spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_exchange_platform
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  mail:
    host: localhost
    port: 1025
    username: abhi
    password: pass
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: HhcQr94Q0PkDdUqSE02jFFwCiQrKR2mQSlJaeOJAogMw
      expiration: 900000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
